name: Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v2
      - run: |
           ls -la
           chmod +x basic_shell.sh
           ls -la
           ./basic_shell.sh
  
