name: Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v2
      - run:
           ls
           sh basic_shell.sh
